### ISSUE TITLE
Summary Email

### ISSUE THREAD

**Issue by sgdavis1** [bioneos/alcove#72]
Summary Emails are broken. I believe it has to do with a difference in the memory data structures that are created at startup (from reading the DB / inspecting the file system) and the way the same structures are created at the end of a successful backup event. Dang dynamically typed language! (We need to switch to TypeScript...)

Here is the relevant error from the logs:
```
[ERROR] Error occurred while generating the Summary Notification: Cannot read property 'eventTime' of undefined
[DEBUG] default - TypeError: Cannot read property 'eventTime' of undefined
    at /usr/share/alcove/lib/system.js:750:44
```

**Comment by dominicrutk** [comment]
https://github.com/bioneos/alcove/commit/267491b830e2cdf42bb2faee8d4eb051c53f43d3
I think this error occurred when the backup system hadn't restarted since the previous summary email. The summary generator only checked for startup events since the last summary, and if it didn't find any, the `processEvents` array was undefined, so accessing `processEvents[0].eventTime` led to that error.
