### ISSUE TITLE
Version number tag

### ISSUE THREAD

**Issue by sgdavis1** [bioneos/alcove#95]
We should add a minimal version number tag to the footer of the app. 

Something like this: 

![image](https://user-images.githubusercontent.com/6651644/122619807-e1dc2d00-d056-11eb-88fa-964b5721aef8.png)

**Comment by dominicrutk** [comment]
Currently, the system logs the version number when starting up:

`[2021-07-08T18:55:59.700] [INFO] default - Bio::Neos Backup System v0.0.5-work starting up!`

This means the version number is pulled into memory from `package.json`, where it is hard coded. Instead of hard coding it in a second place, we should get the number from memory in the controller, and pass it to the template file.

**Comment by ashleyseo** [comment]
I'm doing this one

**Comment by sgdavis1** [comment]
Closed by #106
